### ISSUE TITLE
[Bug]catch_jinja should capture type errors during the rendering phase and display the node information

### ISSUE THREAD

**Issue by devmessias** [dbt-labs/dbt-common#206]
### Is this a new bug in dbt-common?

- [X] I believe this is a new bug in dbt-common
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

As discussed in the following comment by @jeremyyeo https://github.com/dbt-labs/dbt-core/issues/8276#issuecomment-1738130219 on another issue , when there is a type error inside a Jinja template for just one model, the dbt pipeline fails without providing any useful information. I've encountered the same problem several times and spent too much time figuring out what caused it. We can see the same issue appearing in other issues, with users complaining about it: 

https://github.com/dbt-labs/dbt-core/issues/4596#issuecomment-2085768453.

https://github.com/dbt-labs/dbt-core/issues/4596#issuecomment-1021263123

### Expected Behavior

- The user should receive information about the node (model) where the error occurred.

### Steps To Reproduce

```yaml
# dbt_project.yml
name: my_dbt_project
profile: all
config-version: 2
version: 1.0
models:
  my_dbt_project:
    +materialized: table
```

```
-- models/foo.sql
{{ config(materialized=-'table') }}

select 1 id
```

### Relevant log output

```shell
12:23:14  Running with dbt=1.9.0-b2
12:23:14  Registered adapter: duckdb=1.9.0
12:23:14  Encountered an error:
bad operand type for unary -: 'str'
12:23:14  Traceback (most recent call last):
  File "/home/devmessias/phd/pkgs/dbt-my/core/dbt/cli/requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
  File "/home/devmessias/phd/pkgs/dbt-my/core/dbt/cli/requires.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/devmessias/phd/pkgs/dbt-my/core/dbt/cli/requires.py", line 235, in wrapper
    return func(*args, **kwargs)
  File "/home/devmessias/phd/pkgs/dbt-my/core/dbt/cli/requires.py", line 264, in wrapper
    return func(*args, **kwargs)
  File "/home/devmessias/phd/pkgs/dbt-my/core/dbt/cli/requires.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/devmessias/phd/pkgs/dbt-my/core/dbt/cli/requires.py", line 327, in wrapper
    setup_manifest(ctx, write=write, write_perf_info=write_perf_info)
  File "/home/devmessias/phd/pkgs/dbt-my/core/dbt/cli/requires.py", line 351, in setup_manifest
    ctx.obj["manifest"] = parse_manifest(
  File "/home/devmessias/phd/pkgs/dbt-my/core/dbt/parser/manifest.py", line 1998, in parse_manifest
    manifest = ManifestLoader.get_full_manifest(
  File "/home/devmessias/phd/pkgs/dbt-my/core/dbt/parser/manifest.py", line 308, in get_full_manifest
    manifest = loader.load()
  File "/home/devmessias/phd/pkgs/dbt-my/core/dbt/parser/manifest.py", line 413, in load
    self.parse_project(
  File "/home/devmessias/phd/pkgs/dbt-my/core/dbt/parser/manifest.py", line 710, in parse_project
    parser.parse_file(block)
  File "/home/devmessias/phd/pkgs/dbt-my/core/dbt/parser/base.py", line 499, in parse_file
    self.parse_node(file_block)
  File "/home/devmessias/phd/pkgs/dbt-my/core/dbt/parser/base.py", line 468, in parse_node
    self.render_update(node, config)
  File "/home/devmessias/phd/pkgs/dbt-my/core/dbt/parser/models.py", line 349, in render_update
    super().render_update(node, config)
  File "/home/devmessias/phd/pkgs/dbt-my/core/dbt/parser/base.py", line 444, in render_update
    context = self.render_with_context(node, config)
  File "/home/devmessias/phd/pkgs/dbt-my/core/dbt/parser/base.py", line 272, in render_with_context
    get_rendered(parsed_node.raw_code, context, parsed_node, capture_macros=True)
  File "/home/devmessias/phd/pkgs/dbt-my/core/dbt/clients/jinja.py", line 144, in get_rendered
    rendered = render_template(template, ctx, node)
  File "/home/devmessias/phd/pkgs/dbt-common/dbt_common/clients/jinja.py", line 585, in render_template
    return template.render(ctx)
  File "/home/devmessias/phd/pkgs/dbt-common/dbt_common/clients/jinja.py", line 174, in render
    return self.environment.handle_exception()
  File "/home/devmessias/phd/pkgs/dbt-my/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
TypeError: bad operand type for unary -: 'str'
```
```


### Additional Context

I created an issue on dbt-core, but I think here is the correct place https://github.com/dbt-labs/dbt-core/issues/10856

**Comment by dbeatty10** [comment]
@devmessias This is a great idea to avoid that nasty stacktrace in a variety of scenarios 🏆

### Reprex

In addition to the one you provided, here's another reprex (originally offered by @jtcohen6 in and you also included in https://github.com/dbt-labs/dbt-core/issues/10856 that will give an error that says "'NoneType' object is not iterable":

Create this file:

`models/my_model.sql`

```sql
{% set mylist = None %}

{% for item in mylist %}

  select '{{ item }}' as my_item
  {{ 'union all' if not loop.last }}

{% endfor %}
```

Run this command:

```shell
dbt parse
```

**Comment by devmessias** [comment]
Hi @dbeatty10, thanks for pointing out this example. With my PR #207, here is the output:  
![image](https://github.com/user-attachments/assets/312a28b9-68a2-4218-a894-ed87ab4ebdb0)

I'Ve created a new unit test to test if it's correct handling a type error when iterating over a `None` value.

https://github.com/dbt-labs/dbt-common/pull/207/commits/c9b866720b7aa39fbd9113f1eb3dc590659cb96a

I'll wait for the #207 review

**Comment by devmessias** [comment]
Hi @dbeatty10 @gshank, any updates on the PR review for this issue?

**Comment by sriramr98** [comment]
Hey @devmessias. Thanks for the PR. I will have a look at it today and get back to you. Thank you for your patience :D
